@extends('layouts.auth')

@section('title', '2FA Verification')

@section('content')
<h4 class="text-center mb-3">Two-Factor Authentication</h4>
<p class="text-center text-muted-custom small mb-4">Please enter the 6-digit code generated by your authenticator app.</p>

<form method="POST" action="{{ route('login.two-factor.verify') }}">
    @csrf

    <!-- 2FA Code -->
    <div class="mb-4">
        <label for="code" class="form-label">Authentication Code</label>
        <input id="code" type="text" class="form-control text-center fs-4 letter-spacing-lg" name="code" required autofocus autocomplete="one-time-code" placeholder="000 000" maxlength="6">
    </div>

    <!-- Submit Button -->
    <div class="d-grid mb-3">
        <button type="submit" class="btn btn-premium">Verify</button>
    </div>
</form>

<div class="text-center mt-4">
    <a href="{{ route('login') }}" class="small">Back to Sign In</a>
</div>
@endsection
